# Generated by Django 4.2 on 2025-09-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_order_id', models.IntegerField()),
                ('brand_item_id', models.IntegerField()),
                ('order_quantity', models.IntegerField()),
                ('stockexchange_quantity', models.IntegerField(null=True)),
                ('quantity_post_market', models.IntegerField(null=True)),
                ('quantity_at_market', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Order Details',
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_branch_id', models.IntegerField()),
                ('credit', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('debit', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('sale_order_id', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_branch_id', models.IntegerField()),
                ('order_id', models.IntegerField()),
                ('order_date', models.DateTimeField()),
                ('payment_due_date', models.DateTimeField()),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('installment_no', models.IntegerField()),
                ('is_cash_like_payment', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'unique_together': {('order_id', 'installment_no')},
            },
        ),
    ]
