# Generated by Django 4.2 on 2025-09-03 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale_order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Sale Order',
            },
        ),
        migrations.CreateModel(
            name='StockExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('brand_item_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('sale_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_exchanges', to='sale_order.saleorder')),
            ],
            options={
                'verbose_name': 'Stock Exchange',
            },
        ),
        migrations.CreateModel(
            name='ItemSaleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('brand_item_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('sale_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sale_order.saleorder')),
            ],
            options={
                'verbose_name': 'Item Sale Order',
            },
        ),
    ]
