# Generated by Django 4.2 on 2025-09-04 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale_order', '0002_saleorder_stockexchange_itemsaleorder'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemsaleorder',
            unique_together={('sale_order', 'brand_item_id')},
        ),
        migrations.AlterUniqueTogether(
            name='stockexchange',
            unique_together={('sale_order', 'brand_item_id')},
        ),
    ]
