# Generated by Django 4.2 on 2025-08-31 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_payments_credit_alter_payments_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_order_id', models.IntegerField()),
                ('brand_item_id', models.IntegerField()),
                ('stockexchange_quantity', models.IntegerField(null=True)),
                ('quantity_post_market', models.IntegerField(null=True)),
                ('quantity_at_market', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Order Details',
            },
        ),
    ]
