# Generated by Django 4.2 on 2025-08-31 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_orders_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders_details',
            name='order_quantity',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
