# Generated by Django 4.2 on 2025-09-02 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_orders_details_order_quantity'),
    ]

    operations = [

        migrations.DeleteModel(
            name='orders_details',
        ),

    ]
