apiVersion: v1
kind: Service
metadata:
  name: { { .Values.service.name } }
  labels: { app: demoapp-web }
spec:
  type: { { .Values.service.type } }
  selector: { app: demoapp-web }
  ports:
    - port: { { .Values.service.port } }
      targetPort: { { .Values.containerPort } }
      protocol: TCP
      name: http
